### PR TITLE
add header text

### PR DESCRIPTION
**Pull request by yusufhawwah**
Added a SHEros text to a webpage and made it blue.

### CODE REVIEW

**Review by devalibello — CHANGES_REQUESTED** [review]
Hi @yusufhawwah ,

Good job so far!
You still need to work on some issues to get your project approved, but you are almost there!

<div style="text-align:center;">
    Remote Collaboration
</div>

### To Highlight 💯
- **Clean code** 👍
- **Good use of Gitflow** 👍
- **Implemented some project requirements** 👍

### Required Changes ♻️

- Ensure you have a professional PULL REQUEST title. You used `week 1 day 3 project` which doesn't reflect what the PULL REQUEST is about. You can use something like `Add Header Text`

-  Ensure you have a professional PULL REQUEST description too 😊. You used `my activity completion ready for a code review`. You should use something more descriptive. E.g `Added a SHEros text to the webpage and made it blue`

- Remember to re-submit the PR link once you have implemented the changes.

### Optional Suggestions
Every comment with the `[OPTIONAL]` prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding! 👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.  
Please, remember to tag me in your question so I can receive the notification._

**Comment by yusufhawwah** [comment]
I have made the required changes. I changed the pull requests title and description. how do I generate a new link to submit for a second code review? @devalibello

**Comment by devalibello** [comment]
@yusufhawwah Just resubmit the PR link

**Comment by yusufhawwah** [comment]
I have found the link @devalibello but I don't understand the last part of the corrections where you were talking about OPTIONAL prefix in comments. Thank you for your support.

**Comment by devalibello** [comment]
Your project doesn't have any OPTIONAL changes. So just ignore

**Review by Xfarouq — APPROVED** [review]
Hi @yusufhawwah 

Your project is complete! There is nothing else to say other than... it's time to merge it!!!
Congratulations! 🎉

<div style="text-align:center;">
    Remote Collaboration
</div>

### Highlights
- ✅ **Professional Readme**
- ✅ **Good use of Gitflow**
- ✅ **UI looks like the Figma design**
- ✅ **Good use of HTML semantics**
- ✅ **Professional commit messages**
- ✅ **Professional PR title**
- ✅ **Professional PR description**

### Optional Suggestions
Every comment with the `[OPTIONAL]` prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding! 👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.  
Please, remember to tag me in your question so I can receive the notification._

**Pull request merged**
